###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: debug
theme: dark

default_redirection_url: https://authelia.majordoob.com

totp:
  issuer: authelia.com
  period: 30
  skew: 1

authentication_backend:
  file:
    path: /config/users_database.yml
    # customize passwords based on https://docs.authelia.com/configuration/authentication/file.html
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024

# https://docs.authelia.com/configuration/access-control.html
access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: authelia.majordoob.com
      policy: bypass
    - domain: "*.majordoob.com"
      policy: two_factor
    - domain: "majordoob.com"
      policy: two_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # Used a different secret, but the same site as jwt_secret above.
  # secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_SESSION_SECRET_FILE
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: majordoob.com

regulation:
  max_retries: 3
  find_time: 120 # search within the last 2 minutes the user tried to log in
  ban_time: 300  # Ban for five minutes

storage:
  # https://www.authelia.com/docs/configuration/storage/postgres.html
  postgres:
    host: midoriya_db
    port: 5432
    database: midoriya_db
    schema: public
    username: megatron

notifier:
  # smtp:
  #   username: SMTP_USERNAME
  #   # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
  #   # password: # use docker secret file instead AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
  #   host: SMTP_HOST
  #   port: 587 #465
  #   sender: SENDER_EMAIL

  # Delete this when you are done testing
 filesystem:
   filename: /tmp/authelia/notification.txt
