version: '3.7'
services:
  x86_dev_container:
    platform: linux/amd64
    build:
      context: .
      dockerfile: python_dev.dockerfile
    image: python_x86_dev:v1.0
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE

    container_name: x86_dev_container
    volumes:
      - .:/opt/code
    dns:
      - 1.1.1.1
      - 1.0.0.1

    ports:
      - "9999:22"




